// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: athletes.sql

package db

import (
	"context"
	"database/sql"
)

const createAthlete = `-- name: CreateAthlete :execresult
INSERT INTO athletes (name, grade, personal_record, events)
VALUES (?, ?, ?, ?)
`

type CreateAthleteParams struct {
	Name           string  `json:"name"`
	Grade          int8    `json:"grade"`
	PersonalRecord *string `json:"personal_record"`
	Events         *string `json:"events"`
}

func (q *Queries) CreateAthlete(ctx context.Context, arg CreateAthleteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAthlete,
		arg.Name,
		arg.Grade,
		arg.PersonalRecord,
		arg.Events,
	)
}

const deleteAthlete = `-- name: DeleteAthlete :exec
DELETE FROM athletes WHERE id = ?
`

func (q *Queries) DeleteAthlete(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteAthlete, id)
	return err
}

const getAthlete = `-- name: GetAthlete :one
SELECT id, name, grade, personal_record, events, created_at FROM athletes WHERE id = ?
`

func (q *Queries) GetAthlete(ctx context.Context, id int32) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, getAthlete, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PersonalRecord,
		&i.Events,
		&i.CreatedAt,
	)
	return i, err
}

const getFastestPRs = `-- name: GetFastestPRs :many
SELECT id, name, grade, personal_record, events, created_at FROM athletes
WHERE personal_record IS NOT NULL
ORDER BY personal_record ASC
LIMIT ?
`

func (q *Queries) GetFastestPRs(ctx context.Context, limit int32) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, getFastestPRs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PersonalRecord,
			&i.Events,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAthletes = `-- name: ListAthletes :many
SELECT id, name, grade, personal_record, events, created_at FROM athletes ORDER BY name
`

func (q *Queries) ListAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, listAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PersonalRecord,
			&i.Events,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAthletesByGrade = `-- name: ListAthletesByGrade :many
SELECT id, name, grade, personal_record, events, created_at FROM athletes WHERE grade = ? ORDER BY name
`

func (q *Queries) ListAthletesByGrade(ctx context.Context, grade int8) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, listAthletesByGrade, grade)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PersonalRecord,
			&i.Events,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAthlete = `-- name: UpdateAthlete :exec
UPDATE athletes
SET name = ?, grade = ?, personal_record = ?, events = ?
WHERE id = ?
`

type UpdateAthleteParams struct {
	Name           string  `json:"name"`
	Grade          int8    `json:"grade"`
	PersonalRecord *string `json:"personal_record"`
	Events         *string `json:"events"`
	ID             int32   `json:"id"`
}

func (q *Queries) UpdateAthlete(ctx context.Context, arg UpdateAthleteParams) error {
	_, err := q.db.ExecContext(ctx, updateAthlete,
		arg.Name,
		arg.Grade,
		arg.PersonalRecord,
		arg.Events,
		arg.ID,
	)
	return err
}
