// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meets.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createMeet = `-- name: CreateMeet :execresult
INSERT INTO meets (name, date, location, description)
VALUES (?, ?, ?, ?)
`

type CreateMeetParams struct {
	Name        string    `json:"name"`
	Date        time.Time `json:"date"`
	Location    *string   `json:"location"`
	Description *string   `json:"description"`
}

func (q *Queries) CreateMeet(ctx context.Context, arg CreateMeetParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMeet,
		arg.Name,
		arg.Date,
		arg.Location,
		arg.Description,
	)
}

const deleteMeet = `-- name: DeleteMeet :exec
DELETE FROM meets WHERE id = ?
`

func (q *Queries) DeleteMeet(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMeet, id)
	return err
}

const getMeet = `-- name: GetMeet :one
SELECT id, name, date, location, description, created_at FROM meets WHERE id = ?
`

func (q *Queries) GetMeet(ctx context.Context, id int32) (Meet, error) {
	row := q.db.QueryRowContext(ctx, getMeet, id)
	var i Meet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Location,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listMeets = `-- name: ListMeets :many
SELECT id, name, date, location, description, created_at FROM meets ORDER BY date DESC
`

func (q *Queries) ListMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, listMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingMeets = `-- name: ListUpcomingMeets :many
SELECT id, name, date, location, description, created_at FROM meets WHERE date >= CURDATE() ORDER BY date
`

func (q *Queries) ListUpcomingMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeet = `-- name: UpdateMeet :exec
UPDATE meets
SET name = ?, date = ?, location = ?, description = ?
WHERE id = ?
`

type UpdateMeetParams struct {
	Name        string    `json:"name"`
	Date        time.Time `json:"date"`
	Location    *string   `json:"location"`
	Description *string   `json:"description"`
	ID          int32     `json:"id"`
}

func (q *Queries) UpdateMeet(ctx context.Context, arg UpdateMeetParams) error {
	_, err := q.db.ExecContext(ctx, updateMeet,
		arg.Name,
		arg.Date,
		arg.Location,
		arg.Description,
		arg.ID,
	)
	return err
}
