// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Athlete struct {
	ID             int32      `json:"id"`
	Name           string     `json:"name"`
	Grade          int8       `json:"grade"`
	PersonalRecord *string    `json:"personal_record"`
	Events         *string    `json:"events"`
	CreatedAt      *time.Time `json:"created_at"`
}

type Meet struct {
	ID          int32      `json:"id"`
	Name        string     `json:"name"`
	Date        time.Time  `json:"date"`
	Location    *string    `json:"location"`
	Description *string    `json:"description"`
	CreatedAt   *time.Time `json:"created_at"`
}

type Result struct {
	ID        int32      `json:"id"`
	AthleteID int32      `json:"athlete_id"`
	MeetID    int32      `json:"meet_id"`
	Time      string     `json:"time"`
	Place     *int32     `json:"place"`
	CreatedAt *time.Time `json:"created_at"`
}
