// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAthlete(ctx context.Context, arg CreateAthleteParams) (sql.Result, error)
	CreateMeet(ctx context.Context, arg CreateMeetParams) (sql.Result, error)
	CreateResult(ctx context.Context, arg CreateResultParams) (sql.Result, error)
	DeleteAthlete(ctx context.Context, id int32) error
	DeleteMeet(ctx context.Context, id int32) error
	DeleteResult(ctx context.Context, id int32) error
	GetAthlete(ctx context.Context, id int32) (Athlete, error)
	GetFastestPRs(ctx context.Context, limit int32) ([]Athlete, error)
	GetMeet(ctx context.Context, id int32) (Meet, error)
	GetMostRecentMeetResults(ctx context.Context) ([]Result, error)
	GetResult(ctx context.Context, id int32) (Result, error)
	GetResultsByAthlete(ctx context.Context, athleteID int32) ([]Result, error)
	GetResultsByMeet(ctx context.Context, meetID int32) ([]Result, error)
	ListAthletes(ctx context.Context) ([]Athlete, error)
	ListAthletesByGrade(ctx context.Context, grade int8) ([]Athlete, error)
	ListMeets(ctx context.Context) ([]Meet, error)
	ListResults(ctx context.Context) ([]Result, error)
	ListUpcomingMeets(ctx context.Context) ([]Meet, error)
	UpdateAthlete(ctx context.Context, arg UpdateAthleteParams) error
	UpdateMeet(ctx context.Context, arg UpdateMeetParams) error
	UpdateResult(ctx context.Context, arg UpdateResultParams) error
}

var _ Querier = (*Queries)(nil)
